apply plugin: 'com.android.library'

android {
    namespace "com.kony.push.customfcmservice"
    compileSdk 35
    buildToolsVersion "35.0.0"
    
    defaultConfig {
        minSdkVersion 21
        targetSdk 35
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'
    
    // Módulos locales
    implementation project(path: ':kony-push-notifications-apis')
    implementation project(path: ':konywidgets')
    
    // Firebase - Versión estable recomendada para SDK 35
    implementation 'com.google.firebase:firebase-messaging:25.0.1'
}
